mysite/mysite/urls.py
# mysite/urls.py

from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()


from meetingroom.views import hello_world, members, menu

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^hello/$', hello_world),
    url(r'^menu/$', members),
    url(r'^members/$', members),
)

mysite/meetingroom/models.py
from django.db import models

# Create your models here.

# class meetingReserve()
class Meeting(models.Model):
	creater = models.CharField(max_length=40)
	team = models.CharField(max_length=20)
	teamId = models.CharField(max_length=20)
	roomName = models.CharField(max_length=20)
	subject = models.CharField(max_length=40)
	issue = models.CharField(max_length=40)
	meetingType = models.CharField(max_length=10)
	date = models.CharField(max_length=20)
	start_time = models.CharField(max_length=20)
	end_time = models.CharField(max_length=20)
	create_time = models.DateTimeField(auto_now_add=True)
	update_time = models.DateTimeField(auto_now=True)
    

class MembersJoin(models.Model):
	meeting =  models.ForeignKey(Meeting)
	e_mail = models.CharField(max_length=40)

class Member(models.Model):
	firstName = models.CharField(max_length=40)
	lastName = models.CharField(max_length=20)
	nickName = models.CharField(max_length=20)
	e_mail = models.CharField(max_length=40)
	team = models.CharField(max_length=20)
	teamId = models.CharField(max_length=20)
	create_time = models.DateTimeField(auto_now_add=True)
	update_time = models.DateTimeField(auto_now=True)

class Team(models.Model):
	teamName = models.CharField(max_length=20)
	teamId = models.CharField(max_length=20)
	create_time = models.DateTimeField(auto_now_add=True)
	update_time = models.DateTimeField(auto_now=True)

class MeetingRoom(models.Model):
	roomName = models.CharField(max_length=20)
	roomNameId = models.CharField(max_length=20)
	create_time = models.DateTimeField(auto_now_add=True)
	update_time = models.DateTimeField(auto_now=True)

mysite/meetingroom/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, render_to_response
from datetime import datetime

# Create your views here.
def hello_world(request):
    return render(request,
                  'hello_world.html',
                  {'current_time': datetime.now()}
                  )

def menu(request):
	food1 = {'name':'蛋炒飯','price':60,'comment':'好吃','is_spicy':False}
	food2 = {'name':'蒜泥白肉','price':160,'comment':'人氣推薦','is_spicy':True}
	foods =[food1,food2]

	return render_to_response(
                  'menu.html',
                  locals()
                  )
from meetingroom.models import Meeting,MembersJoin

def members(request):
	meetings = Meeting.objects.all()
	return render_to_response('members.html',locals())

mysite/meetingroom/templates/hello_world.html
<!-- hello_world.html -->

<!DOCTYPE html>
<html>
    <head>
        <title>I come from template!!</title>
        <style>
            body {  
               background-color: lightyellow;
            }
            em {
                color: LightSeaGreen;
            }
        </style>
    </head>
    <body>
        <h1>Hello World!</h1>
        <em>{{ current_time }}</em>
    </body>
</html>

mysite/meetingroom/templates/members.html
<!DOCTYPE html>
<html>
<meta charset='utf-8'>

<head>
    <title>會員</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <style>
    th {
        text-align: center;
    }
    
    div.members {
        text-align: center;
        padding: 40px 15px;
    }
    </style>
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only"> Toggle navigation </span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">15mins Metting</a>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="members">
            <p>
                {% for meeting in meetings %}
            <h2>{{ meeting.subject}}</h2>
            {% if meeting.membersjoin_set.all %}
            <p>本會議共有{{ meeting.membersjoin_set.all|length}}個參加人</p>
            <table>
                <tr>
                    <th>email</th>
                    <th>team</th>
                    <th>nick name</th>
                </tr>
                {%for member in meeting.membersjoin_set.all %}
                <tr>
                    <th>{{member.e_mail}}</th>
                    <th> ?</th>
                    <th> ?</th>
                </tr>
                {% endfor %}
            </table>
            </p>
            {%else%}

            <p>本會議目前沒有參加人</p>

            {% endif %}
            {% endfor %}
        </div>
    </div>
</body>
<script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</html>

mysite/meetingroom/templates/menu.html
<!DOCTYPE html>
<html>
<meta charset='utf-8'>
<head>
    <title>會員</title>
    
</head>

<body>
    <p>共有 {{ foods|length}} 個會員 </p>
    {% for food in foods %}
    <h3>第{{ forloop.counter }} 個會員</h3>
    <ul>
        <li>姓:{{food.name}}</li>
        <li>名:{{food.price}}</li>
        <li>e-Mail:{{food.comment}}</li>
        <li>團隊:{{food.price}}</li>
   
    </ul>
    {% endfor %}
</body>

</html>